apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: neo4j-storage-class
provisioner: docker.io/hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
