apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "jmx.password" }}
  {{ . }}: |-
        {{ $files.Get . | b64enc }}
  {{- end }}